### ISSUE TITLE
string comparison failing on namecheap.domains.dns.setCustom ..

### ISSUE THREAD

**Issue by neeksor** [zamnuts/afo-namecheap-api#2]
string comparison failing on namecheap.domains.dns.setCustom ..

[Error: API request and response command type mismatch]

apiRes.RequestedCommand[0] == namecheap.domains.dns.setcustom
apiRes.CommandResponse[0].$.Type == namecheap.domains.dns.setCustom

JSON.stringify(apiRes) 
"$":{"Status":"OK","xmlns":"http://api.namecheap.com/xml.response"},"Errors":[""],"Warnings":[""],"RequestedCommand":["namecheap.domains.dns.setcustom"],"CommandResponse":[{"$":{"Type":"namecheap.domains.dns.setCustom"},"DomainDNSSetCustomResult":[{"$":{"Domain":"x.com","Updated":"true"}}]}],"Server":["PHX01APIEXT02"],"GMTTimeDifference":["--4:00"],"ExecutionTime":["2.728"]}

**Comment by omniadonum** [comment]
Thanks for the PR!

Merged and deployed as v0.3.3.
